server:
  ip: 127.0.0.1
  port: 6666

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
